version: '3.8'

services:
  app:
    build: .
    environment:
      - DATABASE_URL=sqlite:///app/db.sqlite3
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./data:/app/data
      - ./migrations:/app/migrations

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped